### PR TITLE
Enhancement: Add conditionally show/hide forms

### PR DESCRIPTION
**Pull request by ounziw**
Some forms are shown when the condition is met.

Example Usage: When I select "Other", another textarea is shown to fill in the details.

JavaScript codes are updated, following the suggestions by @vrcAlbert
http://forums.novius-os.org/en/support-forums/contributions/noviusos_form-when-select-other-another-textarea-shown-fill-the-details,feed,267.html

### CODE REVIEW

**Comment by jguyomard** [comment]
Thx, nice feature ! :+1:

**Comment by Foine** [comment]
Thank you for this ! :+1:

**Comment by ounziw** [comment]
The reason to this commit is, 
https://github.com/ounziw/noviusos_form/commit/18fe5060e3d56ff7c58c3ea3322f6f2cceb4aefe

You will fill the "field_virtual_name" into the "field_conditional_form".
"field_virtual_name" is shown on "expert view". It is better that "field_conditional_form" is also shown on "expert view".

**Comment by Foine** [comment]
Perfect. Thank you !

**Pull request merged**
