### PR TITLE
Recipient list

### PR DESCRIPTION
**Pull request by smeeckaert**
Hi,

I've added a feature allowing you to set a field determining the recipient for the confirmation mail.

This PR includes : 
- A change in the way select work now allow to specify the value for a select field. On each line, if we find a "=" sign, the left part will be used as the displayed value and the right part as the "hidden" value. (eg. My label=42) will display "My label" and save 42 as a value.
- If a field with an id recipient-list is set, it will be used to change the recipient.
- Added a "Recipient list" type that is a glorified select with explanation and the recipient-list id preset.

### CODE REVIEW

**Comment by Seb-C** [comment]
:+1:

**Comment by Meroje** [comment]
It should warn for email harvesters or hide the emails somehow

**Comment by smeeckaert** [comment]
Do you think we should crypt the email addresses with hmac ?

**Comment by smeeckaert** [comment]
I've added a crypto protection of every select values.

**Comment by Meroje** [comment]
Protecting everything seems dangerous to me, it will make life harder on client side if there is some js working on the value (and potentially break existing clients)

**Comment by Meroje** [comment]
Another concern is getting a raw "=" into any side of the separator, maybe we could allow quoting ("Display = here"="display = here too")  to resolve that ?

**Comment by smeeckaert** [comment]
Okay, i've added the possibility to escape the = sign with a backslash. I also disabled the crypting for select list that doesn't have custom values.

**Comment by Meroje** [comment]
:+1:

**Pull request merged**
